apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-app-secret
  namespace: staging
spec:
  dnsNames:
    - test.rssss.in
  secretName: nginx-app-tls
  issuerRef:
    name: nginx-issuer
    kind: ClusterIssuer