apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: nginx-issuer
  namespace: staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: neeteeshyadav98@gmail.com
    privateKeySecretRef:
      name: nginx-issuer-key
    solvers:
    - http01:
       ingress:
         class: nginx
